"""empty message

Revision ID: 773569db780c
Revises: 
Create Date: 2018-07-09 21:53:45.427020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773569db780c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupoms',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cupoms')
    # ### end Alembic commands ###
